# Generated by Django 3.2.4 on 2021-07-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_alter_taskmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='done',
        ),
    ]
